### ISSUE TITLE
Modal, Toast, Badge Component 만들기

### ISSUE THREAD

**Issue by wise-Ag** [Project-TeamSix/Rolling-Project#16]
## Task
Modal, Toast, Badge Component 만들기

## 작업 내용
- [x] Modal Component
- [x] Toast Component
- [x] RelationBadge(지인,동료, etc) Component

## 주의 사항
- 감사하게도 badge 중 이모지뱃지는 정윤님이 만드셨다네요

**Comment by yunajoe** [comment]
dfsdf

**Comment by lsc58461** [comment]
하하 모르고 만들어버렸네요
